### ISSUE TITLE
I am stuck in downloading modelscope model

### ISSUE THREAD

**Issue by Vinayak-VG** [Picsart-AI-Research/StreamingT2V#46] opened 2024-06-07 15:37 UTC
While making inference, I see that the download bar doesn't progress when downloading the model scope checkpoints. In another GitHub issue suggested that changing regions might help. Is there any work around without changing regions?

**Comment by yxwang-10** [comment] 2024-06-12 01:14
You can manually download the model from huggingface to your local computer, and then manually enter the local path in the modelscope pipeline.

**Comment by niunaicoke** [comment] 2024-07-10 03:21
同问

**Comment by oldnaari** [comment] 2024-08-27 14:20
Closed as this is a duplicate of #32

**Closed by oldnaari** 2024-08-27 14:20 UTC
